apiVersion: batch/v1
kind: Job
metadata:
  name: bert-train
  namespace: kinootziv-app
  annotations:
    argocd.argoproj.io/sync-options: Skip=true,Prune=false
spec:
  template:
    spec:
      containers:
      - name: trainer
        image: fklska/bert-worker:1.58
        imagePullPolicy: Always
        command: ["python3", "train.py"]
        envFrom:
          - configMapRef:
              name: worker-cm
        resources:
          limits:
            cpu: "1000m"
            memory: "8Gi"

      restartPolicy: Never
