apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-migration
  namespace: kinootziv-app
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: migrations
        image: fklska/kino-backend:1.0
        imagePullPolicy: Always
        command: 
          - "sh"
          - "-c"
          - "alembic upgrade head"
      
        envFrom:
        - configMapRef:
            name: backend-cm 
      restartPolicy: Never
