apiVersion: batch/v1
kind: Job
metadata:
  name: regmodel
  annotations:
    argocd.argoproj.io/sync-options: Skip=true,Prune=false
spec:
  template:
    spec:
      containers:
      - name: worker-regmodel
        image: fklska/bert-worker:1.66
        imagePullPolicy: Always
        command: ["python3", "register.py"]
        envFrom:
        - configMapRef:
            name: worker-cm 
      restartPolicy: Never
