apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-cm
  namespace: kinootziv-app
data:
  PROJECT_NAME: "Киноотзыв"
  STACK_NAME: knotzv
  BACKEND_CORS_ORIGINS: "http://localhost,http://localhost:5173,https://localhost,https://localhost:5173,http://localhost.tiangolo.com"
  SECRET_KEY: admin
  FIRST_SUPERUSER: admin@example.com
  FIRST_SUPERUSER_PASSWORD: admin
  POSTGRES_SERVER: postgres-svc
  POSTGRES_PORT: "5432"
  POSTGRES_DB: app
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "1234567"
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest
  RABBITMQ_SERVER: rabbitmq-svc
