apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: kinootziv-app
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.12-management
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5672
          name: "api"
        - containerPort: 15672
          name: "web"

        envFrom:
        - configMapRef:
            name: worker-cm
