apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: kinootziv-app
  labels:
    app: worker
spec:
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: fklska/bert-worker:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "512Mi"
            cpu: "2000m"
        ports:
        - containerPort: 8088

        envFrom:
        - configMapRef:
            name: worker-cm
