apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-cm
  namespace: kinootziv-app
data:
  POSTGRES_SERVER: postgres-svc
  POSTGRES_PORT: "5432"
  POSTGRES_MLFLOW_DB: worker
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "1234567"

  MLFLOW_TRACKING_URI: http://mlflow-svc:5000
  MLFLOW_REGISTER_URI: http://localhost:5000
  MLFLOW_MODEL_URL: models:/bert-imdb@prod

  MLFLOW_S3_ENDPOINT_URL: http://minio-svc:9000
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  GUNICORN_CMD_ARGS: "--workers=1 --threads=1 --max-requests=500 --max-requests-jitter=50"
  BUCKET: mlops

  RABBIT_MQ_URL: amqp://guest:guest@rabbitmq-svc:5672//

  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest