"""Add label&status review

Revision ID: 0c663c6910a5
Revises: 4b0d2a85e769
Create Date: 2026-04-14 14:06:37.980735

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0c663c6910a5"
down_revision: Union[str, Sequence[str], None] = "4b0d2a85e769"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    review_status = postgresql.ENUM("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="review_status")
    review_status.create(op.get_bind())

    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.create_unique_constraint(None, "film", ["title"])
    op.add_column(
        "review",
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "COMPLETED", "FAILED", name="review_status"),
            server_default="PENDING",
            nullable=False,
        ),
    )
    op.add_column("review", sa.Column("label", sa.Integer(), nullable=True))
    op.create_unique_constraint(None, "review", ["title"])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "review", type_="unique")
    op.drop_column("review", "label")
    op.drop_column("review", "status")
    op.drop_constraint(None, "film", type_="unique")
    op.create_table(
        "user",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("user_pkey")),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    review_status = postgresql.ENUM(name="review_status")
    review_status.drop(op.get_bind())
    # ### end Alembic commands ###
