"""add_trained_field

Revision ID: 181e79e1dfa4
Revises: 72ce80a78218
Create Date: 2026-06-09 00:57:45.838870

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "181e79e1dfa4"
down_revision: Union[str, Sequence[str], None] = "72ce80a78218"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("review", sa.Column("trained", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review", "trained")
    # ### end Alembic commands ###
