"""test

Revision ID: 4b0d2a85e769
Revises: 573cc633dc93
Create Date: 2026-03-31 21:00:40.289201

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b0d2a85e769"
down_revision: Union[str, Sequence[str], None] = "573cc633dc93"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("user", sa.Column("id", sa.BigInteger(), nullable=False), sa.PrimaryKeyConstraint("id"))
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
