"""Add label_name

Revision ID: 68be55fe2404
Revises: cde4add24880
Create Date: 2026-05-03 10:09:40.135607

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "68be55fe2404"
down_revision: Union[str, Sequence[str], None] = "cde4add24880"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("review", sa.Column("label_id", sa.Integer(), nullable=True))
    op.alter_column("review", "label", existing_type=sa.INTEGER(), type_=sa.VARCHAR(), existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("review", "label", existing_type=sa.VARCHAR(), type_=sa.INTEGER(), existing_nullable=True)
    op.drop_column("review", "label_id")
    # ### end Alembic commands ###
