"""Add label_name

Revision ID: 986f63d8e925
Revises: 68be55fe2404
Create Date: 2026-05-03 10:16:00.233399

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "986f63d8e925"
down_revision: Union[str, Sequence[str], None] = "68be55fe2404"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("review", sa.Column("probability", sa.DECIMAL(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review", "probability")
    # ### end Alembic commands ###
