"""migrate

Revision ID: d11124601fa5
Revises: 6819aeebdad9
Create Date: 2026-03-31 12:52:51.994963

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d11124601fa5"
down_revision: Union[str, Sequence[str], None] = "6819aeebdad9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("review", "description", existing_type=sa.VARCHAR(), type_=sa.Text(), existing_nullable=False)
    op.drop_column("review", "year")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("review", sa.Column("year", sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column("review", "description", existing_type=sa.Text(), type_=sa.VARCHAR(), existing_nullable=False)
    # ### end Alembic commands ###
