apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-all
  namespace: kinootziv-app
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
spec:
  rules:
  - host: fklska.asuscomm.com
    http:
      paths:
      - path: /adminer
        pathType: Prefix
        backend:
          service:
            name: adminer-svc
            port:
              number: 8080
      - path: /mlflow
        pathType: Prefix
        backend:
          service:
            name: mlflow-svc
            port:
              number: 5000
      - path: /minioapi
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              number: 9000
      - path: /minio
        pathType: Prefix
        backend:
          service:
            name: minio-svc
            port:
              number: 9001
      - path: /grafana
        pathType: Prefix
        backend:
          service:
            name: grafana-svc
            port:
              number: 3000
      - path: /prometheus
        pathType: Prefix
        backend:
          service:
            name: prometheus-svc
            port:
              number: 9090
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kinootziv-svc
            port:
              number: 8000