apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: kinootziv-app
spec:
  resources:
    requests:
      storage: "2Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
