apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: kinootziv-app
spec:
  resources:
    requests:
      storage: "1Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
