apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: kinootziv-app
  labels:
    app: kinootziv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000

        volumeMounts:
        - name: grafana-pv
          mountPath: /var/lib/grafana
        - name: datasourses
          mountPath: /etc/grafana/provisioning/datasources


      volumes:
      - name: grafana-pv
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: datasourses
        configMap:
          name: grafana-cm