apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cm
  namespace: kinootziv-app
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: node-exporter-svc

      - job_name: 'bert-metrics'
        static_configs:
          - targets: ['worker-svc:8088']
