apiVersion: v1
kind: Service
metadata:
  name: evidently-service
  namespace: kinootziv-app
spec:
  selector:
    app: evidently
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  type: ClusterIP