apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-cm
  namespace: kinootziv-app
data:
  GF_SERVER_ROOT_URL: "https://fklska.asuscomm.com:48888/grafana/"
  GF_SERVER_SERVE_FROM_SUB_PATH: "false"
  GF_INSTALL_PLUGINS: "marcusolsson-json-datasource"
  datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-svc:9090
        isDefault: true
