apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: kinootziv-app
spec:
  storageClassName: grafana-manual
  resources:
    requests:
      storage: "1Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
